ToDo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

base/urls.py
from django.urls import path
from . import views 


urlpatterns = [
    path('', views.home, name="home"),
    path('task/<str:pk>/', views.task, name="task"),
    
    
    #CRUD
    path('create-task', views.createTask, name="create-task"),
    path('update-task/<str:pk>/', views.updateTask, name="update-task"),
    path('delete-task/<str:pk>/', views.deleteTask, name="delete-task"),
    
    path('create-tag', views.createTag, name="create-tag"),
    path('update-tag/<str:pk>/', views.updateTag, name="update-tag"),
    

    path('create-list', views.createList, name="create-list"),
    path('update-list/<str:pk>/', views.updateList, name="update-list"),
    
    
    path('create-priority', views.createPriority, name="create-priority"),

    path('create-newpriority', views.createnewPriority, name="create-newpriority"),


    path('update-priority/<str:pk>/', views.updatePriority, name="update-priority"),

    
    path('create-message/<str:pk>/', views.createMessage, name="create-message"),

    path('delete-message/<str:pk>/', views.deleteMessage, name="delete-message"),
    
    
    
]

base/models.py
from django.db import models
from django.contrib.auth.models import User #django pre defined user class

class Tag(models.Model):
    tag = models.CharField(max_length=70)
    
    def __str__(self):
        return self.tag   
   

class List(models.Model): # what list the topics will be in, basically groups
    name = models.CharField(max_length=70)
    
    def __str__(self):
        return self.name    

class Priority(models.Model): # 
    priority = models.CharField(max_length=70)
    tag_color_type = models.CharField(max_length=70, null=True)
    
    def __str__(self):
        return self.priority   
    
class Status(models.Model): # 
    status = models.CharField(max_length=70)
    
    def __str__(self):
        return self.status  
    
           
class Task(models.Model): #consider adding feature later where you can add sub tasks to tasks
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    tag = models.ForeignKey(Tag, on_delete=models.SET_NULL, null=True)
    list = models.ForeignKey(List, on_delete=models.SET_NULL, null=True)
    priority = models.ForeignKey(Priority, on_delete=models.SET_NULL, null=True)
    status = models.ForeignKey(Status, on_delete=models.SET_NULL, null=True)
    
    name = models.CharField(max_length=250)
    description = models.TextField(null=True, blank=True) #null is allowed otherwords this can be blank

    

    update = models.DateTimeField(auto_now=True) # This will take time stamps automatically
    created = models.DateTimeField(auto_now_add=True) # auto_now_add this will be the initial time stamp. so maybe when a room was created
    completed = models.DateTimeField(null=True, blank=True) 
    #^based on status most likely....
    deadline = models.DateTimeField(null=True, blank=True) 
    
   
    def __str__(self):
        return self.name
    
class UpdateMessage(models.Model): # will allow user to make comments and updates on their Task 
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    task = models.ForeignKey(Task, on_delete=models.CASCADE) # on_delete=models.CASCADE when a room is deleted all the messages (children) will be deleted
    body = models.TextField() 
    update = models.DateTimeField(auto_now=True) # This will take time stamps automaticallyt 
    created = models.DateTimeField(auto_now_add=True) # auto_now_add this will be the initial time stamp. so maybe when a room was created
    class Meta: 
        ordering = ['-update', '-created'] 
            
    def __str__(self):
        return self.body #[0:50] #this gets the first 50 characters

base/forms.py
from django.forms import ModelForm
from .models import Tag, List, Task, UpdateMessage, Priority, Status
from django.contrib.auth.models import User #django pre defined user class
from django import forms

class TaskForm(forms.ModelForm): 
   # use_required_attribute = False
    class Meta: 
        model = Task 
        fields = '__all__'
        
        exclude = ['completed', 'user',]
        
    deadline = forms.DateTimeField(
        widget=forms.DateInput(
            attrs={'class': 'form-control',
                    'type':"date"}
        )
    )

class TagForm(ModelForm): 
    class Meta: 
        model = Tag 
        fields = '__all__'
        
class ListForm(ModelForm): 
    class Meta: 
        model = List 
        fields = '__all__'        
       
class PriorityForm(ModelForm):  
    class Meta: 
        model = Priority 
        fields = '__all__'   
        

base/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Tag, List, Task, UpdateMessage, Priority, Status
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from .forms import TaskForm, TagForm, ListForm, PriorityForm
from django.db.models import Q # this will import query stuff to wrap queries
from datetime import datetime


# def createUser(request):
#     form = MyUserCreationForm()

#     if request.method == 'POST':
#         form = MyUserCreationForm(request.POST)
#         if form.is_valid():
#             user = form.save(commit=False)
#             user.username = user.username.lower()
#             user.save()
#             login(request, user)
#             return redirect('home')
#         else:
#             messages.error(request, 'An error occurred during registration')

#     return render(request, 'base/field_form.html', {'form': form})


def home(request):
    q = request.GET.get('q') if request.GET.get('q') != None else '' # empty string is home page so if there's no slug the default will be   
    q_task = request.GET.get('q_task') if request.GET.get('q_task') != None else ''
    tasks = Task.objects.filter(
        Q(tag__tag__icontains = q) | # |   the | means OR 
        Q(list__name__icontains = q) |
        Q(priority__priority__icontains = q) |
        Q(status__status__icontains = q) | 
        Q(name__icontains = q)
        )
    
    task_messages = UpdateMessage.objects.filter(
        Q(task__tag__tag__icontains = q) | # |   the | means OR 
        Q(task__list__name__icontains = q) |
        Q(task__priority__priority__icontains = q) |
        Q(task__status__status__icontains = q)
        )
    
    priority_completed = Task.objects.filter(
        Q(status__status__icontains = q_task) 
        
        )
    # results = request.GET['fruits']
    # print('this is the fruits')
    # print(results)


    # tasks_completed = Task.objects.filter(
    #     Q(status__exact = q_task) 
    #     )
    
    # messages_task_id = task_messages.task
    # name_task = Task.objects.get(name=messages_task_id)
    
    # taskobj = Task.objects.filter(Q(name__icontains = name_task))
    
    #tasks = Task.objects.all()
    tags = Tag.objects.all()
    lists = List.objects.all()
    prioritys = Priority.objects.all()
    statuss = Status.objects.all()
    
    tags_count = tags.count()
    lists_count = lists.count()
    prioritiy_count = prioritys.count()
    tasks_count = tasks.count()
    
    
    context = {'tasks':tasks, 'tags':tags, 'lists':lists,
               'prioritys':prioritys, 'task_messages':task_messages,
                'statuss':statuss, 'priority_completed':priority_completed,
                'tags_count':tags_count, 'lists_count':lists_count, 
                'prioritiy_count':prioritiy_count, 'tasks_count':tasks_count } # 'tasks_completed':tasks_completed,
    
    return render(request, 'base/home.html', context)


def createMessage(request, pk):


    task = Task.objects.get(id=pk)

    if request.method == 'POST':
        message = UpdateMessage.objects.create(
            user=request.user,
            task=task,
            body=request.POST.get('body')
        )
        
    return render(request, 'base/task.html', {})


@login_required(login_url='login')
def deleteMessage(request, pk):
    message = UpdateMessage.objects.get(id=pk)
    message_task_id = message.task
    name_task = Task.objects.get(name=message_task_id)
    
    taskobj = Task.objects.filter(
        Q(name__icontains = name_task))
    taskobj_id = taskobj[0].id

    tasks = Task.objects.all()
    print("taskobj")
    print(taskobj_id)
    

   
   # idd = task_obj.objects.get(id)
    if request.user != message.user: # if they are not the owner of the message
        # return HttpResponse('You are not allowed here')
        reason_message = "Hey guess what? Since you are not logged in"
        message_underline = "you are NOT allowed in here!"

        context = {'reason_message':reason_message, 'message_underline':message_underline, 'name_task':name_task, 'taskobj':taskobj,
        'tasks':tasks}

        
        return render(request, 'base/not_allowed_here.html', context)
    
    if request.method == 'POST':
        
        message.delete()
        
        pk_task = taskobj_id
        return redirect('home')
        
    return render(request, 'base/delete_message.html', {'obj':message, 'taskobj_id':taskobj_id})


def task(request, pk): 
    task = Task.objects.get(id=pk) 
    task_messages = task.updatemessage_set.all().order_by('created') #model name is always lowercase. this will give us the set of messages that are related to this room
    
    statuss = Status.objects.all()
    
    if request.method == 'POST': 
        message = UpdateMessage.objects.create(
            user = request.user,
            task = task,
            body=request.POST.get('body')
            
        )
        
        print("testing body")
        return redirect('task', pk=task.id)
    
    context = {'task':task, 'task_messages':task_messages, 'statuss':statuss}
    
    return render(request, 'base/task.html', context)

@login_required(login_url='login') # this will require that a user is logged in to create a room and redirect them to login page
def createTask(request):
    form = TaskForm()
    
    if request.method =='POST': 
        
        Task.objects.create(
            user = request.user,
            # tag=request.POST.get('tag'),
            # list=request.POST.get('list'),
            # priority=request.POST.get('priority'),
            # status=request.POST.get('status'),
            description=request.POST.get('description'),
            name=request.POST.get('name'),
            # deadline=request.POST.get('deadline'),
        )
    
        return redirect('home') 
    context = {'form':form}
    
    return render(request, 'base/field_form.html', context)


@login_required(login_url='login') # this will require that a user is logged in to create a room and redirect them to login page
def updateTask(request, pk):
    task = Task.objects.get(id=pk)
    form = TaskForm(request.POST or None, instance = task)

    tags = Tag.objects.all()
    lists = List.objects.all()
    prioritys = Priority.objects.all()
    statuss = Status.objects.all()

    # for key, value in statuss.items():
    #     pass
    # print(value)

    
    if request.user != task.user: # if they are not the owner
        reason_message = "Hey guess what? Since you are not logged in"
        message_underline = "you are NOT allowed in here!"

        context = {'reason_message':reason_message, 'message_underline':message_underline}
        return render(request, 'base/not_allowed_here.html', context)

    if request.method =='POST':

        list_task = request.POST.get('list_task')
        list_task_list, created = List.objects.get_or_create(name=list_task)
        task.list = list_task_list

        tag_label = request.POST.get('tag_label')
        status_task_tag, created = Tag.objects.get_or_create(tag=tag_label)
        task.tag = status_task_tag

        status_task = request.POST.get('status_task')
        status_task_status, created = Status.objects.get_or_create(status=status_task)
        task.status = status_task_status

        desc_body = request.POST.get('desc_body')
        task.description = desc_body

        task.save()
        return redirect('home')

        print("here is the list: ")
        print(list_task)

        print("here is the tag_label: ")
        print(tag_label)

        print("here is the status_task: ")
        print(status_task)
        

        print("printing request method here!")
        print(request) 
       

    context = {'form':form, 'task':task, 'tags':tags, 'lists':lists, 'prioritys':prioritys, 'statuss':statuss}
    
    return render(request, 'base/task.html', context)


@login_required(login_url='login')
def deleteTask(request, pk):
    task = Task.objects.get(id=pk)


    # reason_message = "Hey guess what? Since you are not logged in"
    #     message_underline = "you are NOT allowed in here!"

    #     context = {'reason_message':reason_message, 'message_underline':message_underline, 'name_task':name_task, 'taskobj':taskobj,
    #     'tasks':tasks}

        
    #     return render(request, 'base/not_allowed_here.html', context)


    
    if request.user != task.user: # if they are not the owner
        reason_message = "Hey guess what? Since you are not logged in"
        message_underline = "you are NOT allowed in here!"


        context = {'reason_message':reason_message, 'message_underline':message_underline}
        return render(request, 'base/not_allowed_here.html', context)
    
    if request.method == 'POST':
        task.delete()
        return redirect('home')
    
        context = {'obj':task}
        return render(request, 'base/delete.html', context)


def createTag(request):
    form = TagForm()
    if request.method =='POST': 
        
   
        Tag.objects.create(
            tag=request.POST.get('tag'),
        )
    
        return redirect('home') 
    context = {'form':form}
    
    return render(request, 'base/create_tag_form.html', context)


def updateTag(request, pk):
    tag = Tag.objects.get(id=pk)
    form = TagForm(request.POST or None, instance = tag)
   
    if request.method =='POST': 
        if form.is_valid:
            form.save()
            
        return redirect('home')

    context = {'form':form}
    
    return render(request, 'base/field_form.html', context)


def createList(request):
    form = ListForm()
    if request.method =='POST': 
        
        List.objects.create(
            name=request.POST.get('name'),
        )
    
        return redirect('home') 
    context = {'form':form}
        
    return render(request, 'base/field_form.html', context)

base/templates/base/activity_feed.html
{% block content %}

<style>
.content_messages {
    overflow-y: scroll;
    max-height: 300px;
  }
</style>

<div class="card text-white bg-info mb-3" >
  
    <div class="card-body">
      
      <h4 class="card-title">Messages 💬
      </h4>
    
    </div>
    
  </div>



<div class ="content_messages" class="toast show" role="alert" aria-live="assertive" aria-atomic="true">

    {% for message in task_messages %}
        <div class="toast-header">
            {% comment %} <strong class="me-auto"> In Task " {{message.task}} ":</strong> {% endcomment %}
            <strong class="me-auto"> 
                @{{message.user}} 
            </strong>
            <small>
                {{message.created|timesince}} ago
            </small>
        </div>
        <div class="toast-body">
            
    
            {{message.body}}
            <br> 
            <br> 
        <strong>
            <a href="{% url 'task' message.task.id %}">{{message.task}} </a>
    
        </strong>    
           
        </div>
        <hr>
    {% endfor %}
</div>




<br>
<br>
<br>

<div class="query-complete-task">
    {% comment %} <form method="POST" action="{% url 'home' %}">
        <select name="q_task">
            {% for status in statuss %}
                <option value={{status.status}}>{{status.status}}</option>
            {% endfor %}
        </select>
    </form> {% endcomment %}



  

    {% comment %} <form method="POST" action="{% url 'home' %}">
        {% csrf_token %}
        <select name = "q_task">
            <option selected disabled=true>--Select Status Level--</option>
            {% for status in statuss %}
                    <option value={{status.status}}>{{status.status}}</option>
                    {{q_task}}
            {% endfor %}
        </select>
    </form> {% endcomment %}



</div>

<div class="activityfeed-completed-tasks">


    
    <div class="form-group" >
        <div>
          <label for="exampleSelect1" class="form-label mt-4">Change Status</label>

            <form action="{% url 'home' %}?q={{status.status}}">

                <select name="q" class="form-select" id="exampleSelect1">
                    {% for status in statuss %}
                        <option selected="selected" > 
                            <a> {{status.status}}</a>
                        <option>
                    {% endfor %}
                </select>

                <input type="submit" value="click">
            </form>
        </div>
    </div>
      


    <h3>
        Status Lists:
    </h3>

    <div>
    
        {% for priority_complete in priority_completed %}
        
            {{priority_complete.name}}  
            <br>
            
        {% endfor %}
        
        

        

    </div>

</div>

{% endblock content %}

base/templates/base/create_priority_form.html
{% extends 'main.html' %}

{% block content %}

<!-- <div>
    <form method="POST"> 
    {% csrf_token %}
    {{form.as_p}} {% comment %} this puts the fields out in a generic way {% endcomment %}
    <input type="submit" value="Submit" />


</div> -->

<style>
  .priority-layout {
      display: grid;
      grid-template-columns: 1fr 2fr ;
      
  }
  .left {
    grid-column: 1;
    grid-row: 1;
  }

  .right {
    grid-column: 2 ;
    grid-row: 1;
    /* {% comment %} background-color: #2121Z3 {% endcomment %} */
  }
  
  
</style>

<div class="priority-layout">
  <!-- <form class="d-flex" method="GET"> -->
  <div class="left">
    <label class="col-form-label mt-4" name = "priority_text_submit" for="inputDefault">New Priority Name</label>
    {% if num_results > 0 and tracker == 1 %}
    <div class="form-group has-danger">
      <input href="{% url 'create-priority' %}" type="text" value = "{{existing_priority}}" value="Name taken, please try again..." name = "priority_text_submit" class="form-control is-invalid" id="inputInvalid">
      <div class="invalid-feedback">Name taken, please try again...</div>
      <!-- <button class="btn btn-secondary my-2 my-sm-0" value = "button_enter" type="submit">Enter</button> -->

    </div>

    {% elif num_results == 0 and tracker == 1%}

    <div class="form-group has-success">
      <input href="{% url 'create-priority' %}" type="text" value = "{{existing_priority}}" name = "priority_text_submit" class="form-control is-valid" id="inputValid">
      <div class="valid-feedback">Name is valid! </div>
    </div>

    {% else %}

    <div class="form-group">
      
        <input href="{% url 'create-priority' %}" type="text" value = "{{existing_priority}}" class="form-control me-sm-2" placeholder="Input a new Priority name..." name = "priority_text_submit" id="inputDefault">
        <div class="valid-feedback">Input a priority name...</div>
        <!-- <button class="btn btn-secondary my-2 my-sm-0" value = "button_enter" type="submit">Enter</button> -->
      
    </div>

    {% endif %}

    <div>
      
      <fieldset class="form-group">
        <div class="form-check">
          <input class="form-check-input" type="radio" name = "checkbox" value="primary" id="primary">
          <label class="form-check-label" for="flexCheckChecked">
            <span class="badge rounded-pill bg-primary">Primary</span>
        </div>
        <div class="form-check">
          <input class="form-check-input" type="radio" name = "checkbox" value="secondary" id="secondary">
          <label class="form-check-label" for="flexCheckChecked">
            <span class="badge rounded-pill bg-secondary">secondary</span>
        </div>
        <div class="form-check">
          <input class="form-check-input" type="radio" name = "checkbox" value="success" id="success">
          <label class="form-check-label" for="flexCheckChecked">
            <span class="badge rounded-pill bg-success">success</span>
        </div>

        <div class="form-check">
          <input class="form-check-input" type="radio" name = "checkbox" value="danger" id="danger">
          <label class="form-check-label" for="flexCheckChecked">
            <span class="badge rounded-pill bg-danger">danger</span>
        </div>
        <div class="form-check">
          <input class="form-check-input" type="radio" name = "checkbox" value="warning" id="warning">
          <label class="form-check-label" for="flexCheckChecked">
            <span class="badge rounded-pill bg-warning">warning</span>
          
        </div>
        <div class="form-check">
          <input class="form-check-input" type="radio" name = "checkbox" value="info" id="info">
          <label class="form-check-label" for="flexCheckChecked">
            <span class="badge rounded-pill bg-info">info</span>
        </div>

        <div class="form-check">
          <input class="form-check-input" type="radio" name = "checkbox" value="light" id="light">
          <label class="form-check-label" for="flexCheckChecked">
            <span class="badge rounded-pill bg-light">light</span>
        </div>
        
        <div class="form-check">
          <input class="form-check-input" type="radio" name = "checkbox" value="dark" id="dark">
          <label class="form-check-label" for="flexCheckChecked">
            <span class="badge rounded-pill bg-dark">dark</span>
        </div>

    </fieldset>

    </div>
    <form class="" method="POST">
      {% csrf_token %}
      <input href="{% url 'create-priority' %}" class="btn btn-success" name="action"  type="submit"> </input>

    </form>
  </div>
  
</div>

  {% endblock content %}

base/templates/base/manager.html
{% block content %}



  <style>
    /* .header {
    height: 10    
    } */
    
    .content {
      background-color: #f38021;
      overflow-y: scroll;
      max-height: 150px;
      /* {% comment %} background-color: #2121Z3 {% endcomment %} */
    }
    
  </style>



<!-- Tags Start -->
<div>
  <div class="card text-white bg-info mb-3" >
  
    <div class="card-body">
      
      <h4 class="card-title">Tags 🎟️:
    
        <span class="badge bg-dark rounded-pill">{{tags_count}}</span>   
        <a href="{% url 'create-tag' %}" class="btn btn-success float-end" type="submit">Add +</a>
    
      </h4>
    
    </div>
    
  </div>

  <div class="content">
    <ul class="list-group">
      {% for tag in tags %}
      <div>  
        <li class="list-group-item d-flex justify-content-between align-items-center">
          
          <a href="{% url 'home' %}?q={{tag.tag}}" class="btn btn-success" type="submit">{{tag.tag}} f</a>
          
          <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
            <div class="btn-group me-2" role="group" >
              <a href="{% url 'update-tag' tag.id%}"  type="button" class="btn"  >✏️</a>
              <a type="button" class="btn">
                <span class="badge bg-primary rounded-pill">
                  {{tag.task_set.all.count}} 
                </span>    
              </a>
            </div>
          </div>
        </li>


    </div>
    {% endfor %}
    </ul>

  </div>

</div>
<!-- Tags End -->

<!-- Lists Start -->
<div>
  <div class="card text-white bg-info mb-3" >
  
    <div class="card-body">
      
      <h4 class="card-title">Lists 📜:
    
        <span class="badge bg-dark rounded-pill">{{lists_count}}</span>   
        <a href="{% url 'create-list' %}" class="btn btn-success float-end" type="submit">Add +</a>
    
      </h4>
    
    </div>
    
  </div>

  <div class="content">
    <ul class="list-group">

      {% for list in lists %}
      <div>  
        <li class="list-group-item d-flex justify-content-between align-items-center">
          
          <a href="{% url 'home' %}?q={{list.name}}" class="btn btn-success" type="submit">{{list.name}} </a>
          
          <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
            <div class="btn-group me-2" role="group" >
              <a href="{% url 'update-list' list.id%}"  type="button" class="btn"  >✏️</a>
              <a type="button" class="btn">
                <span class="badge bg-primary rounded-pill">
                  {{list.task_set.all.count}}
                </span>    
              </a>
            </div>
          </div>
        </li>


    </div>
    {% endfor %}
    </ul>

  </div>

</div>
<!-- Lists End -->

<!-- Priorities Start -->
<div>

    <div class="card text-white bg-info mb-3" >
 
      <div class="card-body">
        
        <h4 class="card-title">Prioritys 🏁:
      
          <span class="badge bg-dark rounded-pill">{{prioritiy_count}}</span>   
          <a href="{% url 'create-priority' %}" class="btn btn-success float-end" type="submit">Add +</a>
            
        </h4>
      
      
      </div>
      
   
    </div>
  <div class="content">
    <ul class="list-group">
      {% for priority in prioritys %}

          
        {% if "primary" in priority.tag_color_type %}
          
        <li class="list-group-item d-flex justify-content-between align-items-center">
          
          <a href="{% url 'home' %}?q={{priority.priority}}" class="btn btn-primary" type="submit">{{priority.priority}}</a>
          
          <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
            <div class="btn-group me-2" role="group" >
              <a href="{% url 'update-priority' priority.id%}"  type="button" class="btn"  >✏️</a>
              <a type="button" class="btn">
                <span class="badge bg-primary rounded-pill">
                  {{priority.task_set.all.count}}
                </span>    
              </a>
            </div>
          </div>
        </li>
    
      {% elif "secondary" in priority.tag_color_type %}
    
      <li class="list-group-item d-flex justify-content-between align-items-center">
          
        <a href="{% url 'home' %}?q={{priority.priority}}" class="btn btn-secondary" type="submit">{{priority.priority}}</a>
        
        <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
          <div class="btn-group me-2" role="group" >
            <a href="{% url 'update-priority' priority.id%}"  type="button" class="btn"  >✏️</a>
            <a type="button" class="btn">
              <span class="badge bg-primary rounded-pill">
                {{priority.task_set.all.count}}
              </span>    
            </a>
          </div>
        </div>
      </li>
    
      {% elif "success" in priority.tag_color_type %}
    
      <li class="list-group-item d-flex justify-content-between align-items-center">
          
        <a href="{% url 'home' %}?q={{priority.priority}}" class="btn btn-success" type="submit">{{priority.priority}}</a>
        
        <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
          <div class="btn-group me-2" role="group" >
            <a href="{% url 'update-priority' priority.id%}"  type="button" class="btn"  >✏️</a>
            <a type="button" class="btn">
              <span class="badge bg-primary rounded-pill">
                {{priority.task_set.all.count}}
              </span>    
            </a>
          </div>
        </div>
      </li>
    
    
      {% elif "danger" in priority.tag_color_type %}
    
      <li class="list-group-item d-flex justify-content-between align-items-center">
          
        <a href="{% url 'home' %}?q={{priority.priority}}" class="btn btn-danger" type="submit">{{priority.priority}}</a>
        
        <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
          <div class="btn-group me-2" role="group" >
            <a href="{% url 'update-priority' priority.id%}"  type="button" class="btn"  >✏️</a>
            <a type="button" class="btn">
              <span class="badge bg-primary rounded-pill">
                {{priority.task_set.all.count}}
              </span>    
            </a>
          </div>
        </div>
      </li>
      {% elif "warning" in priority.tag_color_type %}
    
      <li class="list-group-item d-flex justify-content-between align-items-center">
          
        <a href="{% url 'home' %}?q={{priority.priority}}" class="btn btn-warning" type="submit">{{priority.priority}}</a>
        
        <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
          <div class="btn-group me-2" role="group" >
            <a href="{% url 'update-priority' priority.id%}"  type="button" class="btn"  >✏️</a>
            <a type="button" class="btn">
              <span class="badge bg-primary rounded-pill">
                {{priority.task_set.all.count}}
              </span>    
            </a>
          </div>
        </div>
      </li>

      {% elif "info" in priority.tag_color_type %}
    
      <li class="list-group-item d-flex justify-content-between align-items-center">
          
        <a href="{% url 'home' %}?q={{priority.priority}}" class="btn btn-info" type="submit">{{priority.priority}}</a>
        
        <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
          <div class="btn-group me-2" role="group" >
            <a href="{% url 'update-priority' priority.id%}"  type="button" class="btn"  >✏️</a>
            <a type="button" class="btn">
              <span class="badge bg-primary rounded-pill">
                {{priority.task_set.all.count}}
              </span>    
            </a>
          </div>
        </div>
      </li>
      {% elif "light" in priority.tag_color_type %}
    
      <li class="list-group-item d-flex justify-content-between align-items-center">
          
        <a href="{% url 'home' %}?q={{priority.priority}}" class="btn btn-light" type="submit">{{priority.priority}}</a>
        
        <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
          <div class="btn-group me-2" role="group" >
            <a href="{% url 'update-priority' priority.id%}"  type="button" class="btn"  >✏️</a>
            <a type="button" class="btn">
              <span class="badge bg-primary rounded-pill">
                {{priority.task_set.all.count}}
              </span>    
            </a>
          </div>
        </div>
      </li>
      {% elif "bg-dark" in priority.tag_color_type %}
    
      <li class="list-group-item d-flex justify-content-between align-items-center">
          
        <a href="{% url 'home' %}?q={{priority.priority}}" class="btn btn-bg-dark" type="submit">{{priority.priority}}</a>
        
        <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
          <div class="btn-group me-2" role="group" >
            <a href="{% url 'update-priority' priority.id%}"  type="button" class="btn"  >✏️</a>
            <a type="button" class="btn">
              <span class="badge bg-primary rounded-pill">
                {{priority.task_set.all.count}}
              </span>    
            </a>
          </div>
        </div>
      </li>
    
      
      {% endif %}

      {% endfor %}
    </ul>
  </div>
</div>
<!-- Priorities End -->



  


  
{% endblock content %}